# Generated by Django 3.2.24 on 2024-03-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='cat_image1',
        ),
    ]
